/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/question-sets/{questionSetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 셋 단건 조회 */
        get: operations["getQuestionSet"];
        /**
         * 문제 셋을 최종 저장 API
         * @description 문제 셋을 제작 완료 상태로 변경
         */
        put: operations["completeQuestionSet"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 문제 셋 제목 단건 수정 API
         * @description 연필 버튼 클릭을 통한 문제 셋 단건 수정
         */
        patch: operations["updateQuestionSet"];
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 조회 API */
        get: operations["getQuestion"];
        /**
         * 문제 단건 수정 API
         * @description 문제 셋의 특정 번호의 문제를 수정
         */
        put: operations["updateQuestion"];
        post?: never;
        /**
         * 문제 단건 삭제 API
         * @description 생성 중인 문제 단건 삭제를 진행
         */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 다음 문제 진출자 조회 */
        get: operations["getActiveParticipants"];
        /** 다음 문제 진출자 수정 */
        put: operations["updateActiveParticipants"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 팀 생성 API */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 셋 목록 조회 */
        get: operations["getQuestionSets"];
        put?: never;
        /**
         * 문제 셋 생성 API
         * @description 새로운 문제 셋을 생성합니다.
         */
        post: operations["createQuestionSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 셋에 속한 모든 문제 조회 API */
        get: operations["getQuestions"];
        put?: never;
        /**
         * 문제 셋에 문제 저장 API
         * @description 문제 셋에 문제를 유형별로 단건 업로드 한다.
         */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 문제 풀이 정답 제출 API */
        post: operations["submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/control/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["allowQuestionSolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/control/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["allowQuestionAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 기본 문제 생성 API
         * @description 문제 생성 과정에서 추가 버튼을 통해 기본 문제를 생성한다.
         */
        post: operations["createDefaultQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/winner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 우승자 전송 */
        post: operations["sendWinner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인 API
         * @description 사용자 로그인 API
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 실시간 문제셋 시작 */
        patch: operations["startLiveQuestionSet"];
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 실시간 문제셋 종료 */
        patch: operations["endLiveQuestionSet"];
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 정보 반환 */
        get: operations["getUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/submit-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 풀이 정답 제출 기록 조회 API */
        get: operations["getSubmitRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/scorer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제별 득점자 조회 API */
        get: operations["getScorer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실시간 문제셋 상태 조회 */
        get: operations["getLiveStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/rank/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실시간 문제셋 정답자 랭킹 */
        get: operations["getCorrectAnswerRank"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/current-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실시간 진행중 문제 */
        get: operations["getCurrentQuestionId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Access token 반환 API
         * @description Oauth 로그인 후 access token을 반환하는 API
         */
        get: operations["getAccessToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 문제 풀이 방식
         * @enum {string}
         */
        DeliveryMode: "MAKING" | "LIVE_TIME" | "REVIEW";
        /**
         * @description 문제 셋 공개 단위
         * @enum {string}
         */
        QuestionSetVisibility: "PUBLIC" | "GROUP" | "PRIVATE";
        UpdateQuestionSetApiRequest: {
            /** @description 문제 셋 제목 */
            title: string;
            /** @description 문제 셋 주제 */
            subject: string;
            mode?: components["schemas"]["DeliveryMode"];
            /** @description 문제 셋 난이도 설명 */
            levelDescription?: string;
            visibility?: components["schemas"]["QuestionSetVisibility"];
        };
        ApiResponseQuestionSetApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionSetApiResponse"];
        };
        QuestionSetApiResponse: {
            /** Format: int64 */
            id: number;
            subject?: string;
            title?: string;
            creationType: components["schemas"]["QuestionSetCreationType"];
            visibility: components["schemas"]["QuestionSetVisibility"];
            deliveryMode: components["schemas"]["DeliveryMode"];
            /** Format: int64 */
            teamId: number;
            /** Format: int64 */
            questionCount: number;
            levelDescription?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description 문제 셋 생성 유형
         * @enum {string}
         */
        QuestionSetCreationType: "AI_GENERATED" | "MANUAL";
        FillBlankAnswerDto: {
            /** Format: int64 */
            id?: number;
            answer?: string;
            /**
             * Format: int64
             * @description 빈칸 문제 정답 그룹 번호
             */
            number: number;
            main?: boolean;
        };
        MultipleChoiceDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            number: number;
            content: string;
            isCorrect: boolean;
        };
        OrderingQuestionOptionDto: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: int32
             * @description 보기에 보여질 순서
             */
            originOrder: number;
            /** @description 보기 내용 */
            content: string;
            /**
             * Format: int32
             * @description 정답이 되는 순서
             */
            answerOrder?: number;
        };
        ShortAnswerDto: {
            /** Format: int64 */
            id?: number;
            answer?: string;
            /**
             * Format: int64
             * @description 주관식 문제 정답 그룹 번호
             */
            number: number;
            main?: boolean;
        };
        UpdateFillBlankQuestionApiRequest: {
            type: "UpdateFillBlankQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["UpdateQuestionApiRequest"], "number" | "type">, "type"> & {
            fillBlankAnswers: components["schemas"]["FillBlankAnswerDto"][];
        });
        UpdateMultipleQuestionApiRequest: {
            type: "UpdateMultipleQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["UpdateQuestionApiRequest"], "number" | "type">, "type"> & {
            choices: components["schemas"]["MultipleChoiceDto"][];
        });
        UpdateOrderingQuestionApiRequest: {
            type: "UpdateOrderingQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["UpdateQuestionApiRequest"], "number" | "type">, "type"> & {
            options: components["schemas"]["OrderingQuestionOptionDto"][];
        });
        UpdateQuestionApiRequest: {
            /** Format: int64 */
            id?: number;
            content?: string;
            explanation?: string;
            /**
             * Format: int64
             * @description 문제 번호, 단 문제 번호는 변경되지 않음
             */
            number: number;
            type: string;
        };
        UpdateShortQuestionApiRequest: {
            type: "UpdateShortQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["UpdateQuestionApiRequest"], "number" | "type">, "type"> & {
            shortAnswers: components["schemas"]["ShortAnswerDto"][];
        });
        ApiResponseQuestionApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["FillBlankQuestionApiResponse"] | components["schemas"]["MultipleQuestionApiResponse"] | components["schemas"]["OrderingQuestionApiResponse"] | components["schemas"]["ShortQuestionApiResponse"];
        };
        /** @description 빈칸 문제의 정답 목록 */
        FillBlankAnswerApiResponse: {
            /**
             * Format: int64
             * @description 빈칸 문제 답안 ID
             */
            id: number;
            answer?: string;
            /** @description 빈칸 문제 답안이 주관식인지 객관식인지 여부 */
            isMain: boolean;
            /**
             * Format: int64
             * @description 빈칸 문제 답안의 순서
             */
            number: number;
        };
        FillBlankQuestionApiResponse: {
            type: "FillBlankQuestionApiResponse";
        } & (Omit<WithRequired<components["schemas"]["QuestionApiResponse"], "id" | "number" | "type">, "type"> & {
            /** @description 빈칸 문제의 정답 목록 */
            answers?: components["schemas"]["FillBlankAnswerApiResponse"][];
            /**
             * Format: int32
             * @description 빈칸의 개수
             */
            blankCount: number;
        });
        /** @description 객관식 문제의 선택지 목록 */
        MultipleChoiceApiResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            number: number;
            content?: string;
            isCorrect: boolean;
        };
        MultipleQuestionApiResponse: {
            type: "MultipleQuestionApiResponse";
        } & (Omit<WithRequired<components["schemas"]["QuestionApiResponse"], "id" | "number" | "type">, "type"> & {
            /** @description 객관식 문제의 선택지 목록 */
            choices: components["schemas"]["MultipleChoiceApiResponse"][];
        });
        /** @description 순서 문제의 보기 목록 */
        OrderingOptionApiResponse: {
            /**
             * Format: int64
             * @description 정렬 문제 옵션 ID
             */
            id: number;
            /**
             * Format: int32
             * @description 정렬 문제 옵션의 원래 순서
             */
            originOrder: number;
            content?: string;
            /**
             * Format: int32
             * @description 정렬 문제 옵션의 답안 순서
             */
            answerOrder?: number;
        };
        OrderingQuestionApiResponse: {
            type: "OrderingQuestionApiResponse";
        } & (Omit<WithRequired<components["schemas"]["QuestionApiResponse"], "id" | "number" | "type">, "type"> & {
            /** @description 순서 문제의 보기 목록 */
            options: components["schemas"]["OrderingOptionApiResponse"][];
        });
        QuestionApiResponse: {
            /** Format: int64 */
            id: number;
            content?: string;
            explanation?: string;
            /** Format: int64 */
            number: number;
            /** @enum {string} */
            type: "SHORT" | "MULTIPLE" | "ORDERING" | "FILL_BLANK";
            /** @enum {string} */
            questionStatusType?: "NOT_OPEN" | "ACCESS_PERMISSION" | "SOLVE_PERMISSION";
        };
        /** @description 주관식 문제의 정답 목록 */
        ShortAnswerApiResponse: {
            /** Format: int64 */
            id: number;
            answer?: string;
            isMain: boolean;
            /** Format: int64 */
            number: number;
        };
        ShortQuestionApiResponse: {
            type: "ShortQuestionApiResponse";
        } & (Omit<WithRequired<components["schemas"]["QuestionApiResponse"], "id" | "number" | "type">, "type"> & {
            /** @description 주관식 문제의 정답 목록 */
            answers?: components["schemas"]["ShortAnswerApiResponse"][];
            /**
             * Format: int32
             * @description 주관식 문제의 정답 개수
             */
            answerCount: number;
        });
        UpdateActiveParticipantsRequest: {
            activeUserIds?: number[];
        };
        ApiResponseVoid: {
            isSuccess?: boolean;
            data?: Record<string, never>;
        };
        CreateTeamApiRequest: {
            name: string;
        };
        CreateQuestionSetApiRequest: {
            subject: string;
            /** @enum {string} */
            creationType: "AI_GENERATED" | "MANUAL";
        };
        ApiResponseCreateQuestionSetApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["CreateQuestionSetApiResponse"];
        };
        CreateQuestionSetApiResponse: {
            /**
             * Format: int64
             * @description 생성된 문제 셋의 ID
             */
            questionSetId: number;
            /** @description 문제 셋 주제 */
            subject: string;
        };
        CreateFillBlankQuestionApiRequest: {
            type: "CreateFillBlankQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["CreateQuestionApiRequest"], "number">, "type"> & {
            fillBlankAnswers: components["schemas"]["FillBlankAnswerDto"][];
        });
        CreateMultipleQuestionApiRequest: {
            type: "CreateMultipleQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["CreateQuestionApiRequest"], "number">, "type"> & {
            choices: components["schemas"]["MultipleChoiceDto"][];
        });
        CreateOrderingQuestionApiRequest: {
            type: "CreateOrderingQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["CreateQuestionApiRequest"], "number">, "type"> & {
            options: components["schemas"]["OrderingQuestionOptionDto"][];
        });
        CreateQuestionApiRequest: {
            content?: string;
            explanation?: string;
            /** Format: int64 */
            number: number;
            type: string;
        };
        CreateShortQuestionApiRequest: {
            type: "CreateShortQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["CreateQuestionApiRequest"], "number">, "type"> & {
            shortAnswers: components["schemas"]["ShortAnswerDto"][];
        });
        FillBlankQuestionSubmitApiRequest: {
            type: "FillBlankQuestionSubmitApiRequest";
        } & (Omit<WithRequired<components["schemas"]["QuestionAnswerSubmitApiRequest"], "submitAnswers" | "userId">, "type"> & {
            submitAnswers: components["schemas"]["SubmitAnswerDtoFillBlankSubmitAnswer"];
        });
        FillBlankSubmitAnswer: {
            /** Format: int64 */
            number: number;
            answer: string;
        };
        MultipleQuestionSubmitApiRequest: {
            type: "MultipleQuestionSubmitApiRequest";
        } & (Omit<WithRequired<components["schemas"]["QuestionAnswerSubmitApiRequest"], "submitAnswers" | "userId">, "type"> & {
            submitAnswers: components["schemas"]["SubmitAnswerDtoLong"];
        });
        OrderingQuestionSubmitApiRequest: {
            type: "OrderingQuestionSubmitApiRequest";
        } & (Omit<WithRequired<components["schemas"]["QuestionAnswerSubmitApiRequest"], "submitAnswers" | "userId">, "type"> & {
            submitAnswers: components["schemas"]["SubmitAnswerDtoLong"];
        });
        QuestionAnswerSubmitApiRequest: {
            /**
             * Format: int64
             * @description 문제 PK, 추후에 삭제 예정
             */
            userId: number;
            submitAnswers?: components["schemas"]["SubmitAnswerDtoObject"];
            type: string;
        };
        /** @enum {string} */
        QuestionType: "SHORT" | "MULTIPLE" | "ORDERING" | "FILL_BLANK";
        ShortQuestionSubmitApiRequest: {
            type: "ShortQuestionSubmitApiRequest";
        } & (Omit<WithRequired<components["schemas"]["QuestionAnswerSubmitApiRequest"], "submitAnswers" | "userId">, "type"> & {
            submitAnswers: components["schemas"]["SubmitAnswerDtoString"];
        });
        SubmitAnswerDtoFillBlankSubmitAnswer: {
            type?: components["schemas"]["QuestionType"];
            submitAnswers?: components["schemas"]["FillBlankSubmitAnswer"][];
        };
        SubmitAnswerDtoLong: {
            type?: components["schemas"]["QuestionType"];
            submitAnswers?: number[];
        };
        SubmitAnswerDtoObject: {
            type?: components["schemas"]["QuestionType"];
            submitAnswers?: Record<string, never>[];
        };
        SubmitAnswerDtoString: {
            type?: components["schemas"]["QuestionType"];
            submitAnswers?: string[];
        };
        ApiResponseQuestionAnswerSubmitApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionAnswerSubmitApiResponse"];
        };
        QuestionAnswerSubmitApiResponse: {
            /**
             * Format: int64
             * @description 제출한 기록 PK
             */
            id: number;
            /**
             * Format: int64
             * @description 제출한 유저 PK
             */
            userId: number;
            /**
             * Format: int64
             * @description 제출한 문제 PK
             */
            questionId: number;
            /** @description 정/오답 여부 */
            isCorrect: boolean;
        };
        CreateDefaultQuestionApiRequest: {
            /**
             * Format: int64
             * @description 문제 번호
             */
            number: number;
        };
        SendWinnerRequest: {
            winnerUserIds?: number[];
        };
        LoginApiRequest: {
            email: string;
            password: string;
        };
        UpdateQuestionSetFieldApiRequest: {
            title: string;
        };
        ApiResponseUserInfoApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["UserInfoApiResponse"];
        };
        UserInfoApiResponse: {
            /**
             * Format: int64
             * @description 사용자 ID
             */
            id?: number;
            /** @description 사용자 이름 */
            name?: string;
            /** @description 사용자 이메일 */
            email?: string;
            /** @description 사용자 닉네임 */
            nickname?: string;
        };
        ApiResponseListQuestionSetApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionSetApiResponse"][];
        };
        ApiResponseListQuestionApiResponse: {
            isSuccess?: boolean;
            data?: (components["schemas"]["FillBlankQuestionApiResponse"] | components["schemas"]["MultipleQuestionApiResponse"] | components["schemas"]["OrderingQuestionApiResponse"] | components["schemas"]["ShortQuestionApiResponse"])[];
        };
        ApiResponseListQuestionAnswerSubmitRecordApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionAnswerSubmitRecordApiResponse"][];
        };
        QuestionAnswerSubmitRecordApiResponse: {
            /**
             * Format: int64
             * @description 제출 기록 PK
             */
            id: number;
            /**
             * Format: int64
             * @description 제출한 유저 PK
             */
            userId: number;
            /** @description 제출한 유저 이름 */
            userName?: string;
            /**
             * Format: int64
             * @description 제출한 문제 PK
             */
            questionId: number;
            /** @description 정/오답 여부 */
            isCorrect: boolean;
            /**
             * Format: int64
             * @description 제출 순서
             */
            submitOrder: number;
        };
        ApiResponseQuestionScorerApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionScorerApiResponse"];
        };
        QuestionScorerApiResponse: {
            /**
             * Format: int64
             * @description 득점자 PK
             */
            id: number;
            /**
             * Format: int64
             * @description 문제 PK
             */
            questionId: number;
            /**
             * Format: int64
             * @description 득점한 사용자 PK
             */
            userId?: number;
            /** @description 득점한 사용자 이름 */
            userName?: string;
            /**
             * Format: int64
             * @description 득점 순서
             */
            submitOrder?: number;
        };
        ApiResponseQuestionSetLiveStatusResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionSetLiveStatusResponse"];
        };
        QuestionSetLiveStatusResponse: {
            /** Format: int64 */
            questionSetId?: number;
            /** @enum {string} */
            liveStatus?: "BEFORE_LIVE" | "LIVE" | "AFTER_LIVE";
        };
        ApiResponseParticipantsCorrectAnswerRankResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["ParticipantsCorrectAnswerRankResponse"];
        };
        ParticipantCorrectAnswerResponse: {
            participantInfos?: components["schemas"]["ParticipantInfoResponse"];
            /** Format: int64 */
            correctAnswerCount?: number;
        };
        ParticipantInfoResponse: {
            /**
             * Format: int64
             * @description 진출 유저 ID
             */
            userId: number;
            /**
             * Format: int64
             * @description 참여자 ID
             */
            participantId: number;
            /** @description 참여자 이름 */
            participantName: string;
        };
        ParticipantsCorrectAnswerRankResponse: {
            activeParticipants?: components["schemas"]["ParticipantCorrectAnswerResponse"][];
            eliminatedParticipants?: components["schemas"]["ParticipantCorrectAnswerResponse"][];
        };
        ApiResponseListParticipantInfoResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["ParticipantInfoResponse"][];
        };
        ApiResponseCurrentQuestionApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["CurrentQuestionApiResponse"];
        };
        CurrentQuestionApiResponse: {
            /** Format: int64 */
            questionSetId?: number;
            /** Format: int64 */
            questionId?: number;
            /** @enum {string} */
            questionStatusType?: "NOT_OPEN" | "ACCESS_PERMISSION" | "SOLVE_PERMISSION";
        };
        ApiResponseString: {
            isSuccess?: boolean;
            data?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSetApiResponse"];
                };
            };
        };
    };
    completeQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionSetApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSetApiResponse"];
                };
            };
        };
    };
    updateQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionSetFieldApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getQuestion: {
        parameters: {
            query?: {
                mode?: "MAKING" | "LIVE_TIME" | "REVIEW";
            };
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionApiResponse"];
                };
            };
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFillBlankQuestionApiRequest"] | components["schemas"]["UpdateMultipleQuestionApiRequest"] | components["schemas"]["UpdateOrderingQuestionApiRequest"] | components["schemas"]["UpdateShortQuestionApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionApiResponse"];
                };
            };
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getActiveParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListParticipantInfoResponse"];
                };
            };
        };
    };
    updateActiveParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActiveParticipantsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getQuestionSets: {
        parameters: {
            query: {
                mode: "MAKING" | "LIVE_TIME" | "REVIEW";
                teamId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionSetApiResponse"];
                };
            };
        };
    };
    createQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionSetApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCreateQuestionSetApiResponse"];
                };
            };
        };
    };
    getQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionApiResponse"];
                };
            };
        };
    };
    createQuestion: {
        parameters: {
            query: {
                type: string;
            };
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFillBlankQuestionApiRequest"] | components["schemas"]["CreateMultipleQuestionApiRequest"] | components["schemas"]["CreateOrderingQuestionApiRequest"] | components["schemas"]["CreateShortQuestionApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FillBlankQuestionSubmitApiRequest"] | components["schemas"]["MultipleQuestionSubmitApiRequest"] | components["schemas"]["OrderingQuestionSubmitApiRequest"] | components["schemas"]["ShortQuestionSubmitApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionAnswerSubmitApiResponse"];
                };
            };
        };
    };
    allowQuestionSolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    allowQuestionAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    createDefaultQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDefaultQuestionApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionApiResponse"];
                };
            };
        };
    };
    sendWinner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendWinnerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    startLiveQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    endLiveQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserInfoApiResponse"];
                };
            };
        };
    };
    getSubmitRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionAnswerSubmitRecordApiResponse"];
                };
            };
        };
    };
    getScorer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionScorerApiResponse"];
                };
            };
        };
    };
    getLiveStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSetLiveStatusResponse"];
                };
            };
        };
    };
    getCorrectAnswerRank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseParticipantsCorrectAnswerRankResponse"];
                };
            };
        };
    };
    getCurrentQuestionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCurrentQuestionApiResponse"];
                };
            };
        };
    };
    getAccessToken: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
