/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/question-sets/{questionSetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 셋 단건 조회 */
        get: operations["getQuestionSet"];
        /**
         * 문제 셋을 최종 저장 API
         * @description 문제 셋을 제작 완료 상태로 변경
         */
        put: operations["completeQuestionSet"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 문제 셋 제목 단건 수정 API
         * @description 연필 버튼 클릭을 통한 문제 셋 단건 수정
         */
        patch: operations["updateQuestionSet"];
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 조회 API */
        get: operations["getQuestion"];
        /**
         * 문제 단건 수정 API
         * @description 문제 셋의 특정 번호의 문제를 수정
         */
        put: operations["updateQuestion"];
        post?: never;
        /**
         * 문제 단건 삭제 API
         * @description 생성 중인 문제 단건 삭제를 진행
         */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 다음 문제 진출자 조회 */
        get: operations["getActiveParticipants"];
        /** 다음 문제 진출자 수정 */
        put: operations["updateActiveParticipants"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 팀 생성 API */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 팀 초대 링크 생성 API */
        post: operations["createTeamInviteCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 셋 목록 조회 */
        get: operations["getQuestionSets"];
        put?: never;
        /**
         * 문제 셋 생성 API
         * @description 새로운 문제 셋을 생성합니다.
         */
        post: operations["createQuestionSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 셋에 속한 모든 문제 조회 API */
        get: operations["getQuestions"];
        put?: never;
        /**
         * 문제 셋에 문제 저장 API
         * @description 문제 셋에 문제를 유형별로 단건 업로드 한다.
         */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 문제 풀이 정답 제출 API */
        post: operations["submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/control/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["allowQuestionSolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/control/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["allowQuestionAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 문제 정답 추가 API
         * @description 실시간 풀이 진행 중 특정 문제의 정답을 추가한다.
         */
        post: operations["regradeQuestionSubmitRecords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 문제 이미지 업로드 API
         * @description 문제에 이미지를 업로드합니다.
         */
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 기본 문제 생성 API
         * @description 문제 생성 과정에서 추가 버튼을 통해 기본 문제를 생성한다.
         */
        post: operations["createDefaultQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/winner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 우승자 전송 */
        post: operations["sendWinner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 문제 셋에 사용될 파일 업로드 API
         * @description 문제 셋 생성 과정에서 사용될 파일을 업로드합니다.
         */
        post: operations["uploadQuestionSetFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 정책 동의/미동의 처리
         * @description 여러 정책에 대해 동의 또는 미동의를 한번에 처리합니다.
         */
        post: operations["checkPolicies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인 API
         * @description 사용자 로그인 API
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 사용자 닉네임 변경 */
        patch: operations["updateUserNickname"];
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 문제 순서 변경 API
         * @description 문제 셋에 속한 문제들의 순서를 변경
         */
        patch: operations["changeQuestionOrder"];
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 실시간 문제셋 시작 */
        patch: operations["startLiveQuestionSet"];
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 실시간 문제셋 종료 */
        patch: operations["endLiveQuestionSet"];
        trace?: never;
    };
    "/api/v1/users/nickname/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 랜덤 닉네임 반환 */
        get: operations["getRandomNickname"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 정보 반환 */
        get: operations["getUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/submit-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 풀이 정답 제출 기록 조회 API */
        get: operations["getSubmitRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/questions/{questionId}/scorer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제별 득점자 조회 API */
        get: operations["getScorer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실시간 문제셋 상태 조회 */
        get: operations["getLiveStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/rank/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실시간 문제셋 정답자 랭킹 */
        get: operations["getCorrectAnswerRank"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/live-status/current-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실시간 진행중 문제 */
        get: operations["getCurrentQuestionId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/{questionSetId}/ai-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI 문제 제작 상태 조회
         * @description AI 문제 제작 상태를 조회합니다.
         */
        get: operations["getAiRequestStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문제 셋 전체 문제 검증 API
         * @description 문제 셋 전체 문제를 검증 후 조건을 만족하지 않는 문제 목록을 반환한다.
         */
        get: operations["validateQuestionSet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 타이밍별 최신 정책 목록 조회 */
        get: operations["findLatestPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/unchecked/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 타이밍별 미확인 정책 목록 조회 */
        get: operations["findUnConfirmedPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Access token 반환 API
         * @description Oauth 로그인 후 access token을 반환하는 API
         */
        get: operations["getAccessToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 문제 풀이 방식
         * @enum {string}
         */
        DeliveryMode: "MAKING" | "LIVE_TIME" | "REVIEW";
        /**
         * @description 문제 셋 공개 단위
         * @enum {string}
         */
        QuestionSetVisibility: "PUBLIC" | "GROUP" | "PRIVATE";
        UpdateQuestionSetApiRequest: {
            /** @description 문제 셋 제목 */
            title: string;
            /** @description 문제 셋 주제 */
            subject: string;
            mode?: components["schemas"]["DeliveryMode"];
            /** @description 문제 셋 난이도 설명 */
            difficulty?: string;
            visibility?: components["schemas"]["QuestionSetVisibility"];
        };
        ApiResponseQuestionSetApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionSetApiResponse"];
        };
        QuestionSetApiResponse: {
            /** Format: int64 */
            id: number;
            /** @description 문제 셋에서 다루는 주제 */
            /** @description 문제 셋에서 다루는 주제 */
            subject?: string;
            /** @description 문제 셋 제목 */
            /** @description 문제 셋 제목 */
            title?: string;
            creationType: components["schemas"]["QuestionSetCreationType"];
            visibility: components["schemas"]["QuestionSetVisibility"];
            deliveryMode: components["schemas"]["DeliveryMode"];
            /** Format: int64 */
            teamId: number;
            ongoingStatus?: components["schemas"]["QuestionSetOngoingStatus"];
            ongoingStatus?: components["schemas"]["QuestionSetOngoingStatus"];
            /** Format: int64 */
            questionCount: number;
            difficulty?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description 문제 셋 생성 유형
         * @enum {string}
         */
        QuestionSetCreationType: "AI_GENERATED" | "MANUAL";
        /**
         * @description 문제 셋 진행 상태
         * @enum {string}
         */
        QuestionSetOngoingStatus: "BEFORE" | "ONGOING" | "AFTER";
        /**
         * @description 문제 셋 진행 상태
         * @enum {string}
         */
        QuestionSetOngoingStatus: "BEFORE" | "ONGOING" | "AFTER";
        FillBlankAnswerDto: {
            /** Format: int64 */
            id?: number;
            answer?: string;
            /** @description 빈칸 문제의 메인 정답 여부 */
            main: boolean;
            /**
             * Format: int64
             * @description 빈칸 문제 정답 그룹 번호
             */
            number: number;
        };
        MultipleChoiceDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            number: number;
            content: string;
            isCorrect: boolean;
        };
        OrderingQuestionOptionDto: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: int32
             * @description 보기에 보여질 순서
             */
            originOrder: number;
            /** @description 보기 내용 */
            content: string;
            /**
             * Format: int32
             * @description 정답이 되는 순서
             */
            answerOrder?: number;
        };
        ShortAnswerDto: {
            /** Format: int64 */
            id?: number;
            answer?: string;
            /** @description 주관식 문제의 메인 정답 여부 */
            main: boolean;
            /**
             * Format: int64
             * @description 주관식 문제 정답 그룹 번호
             */
            number: number;
        };
        UpdateFillBlankQuestionApiRequest: {
            type: "UpdateFillBlankQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["UpdateQuestionApiRequest"], "number">, "type"> & {
            fillBlankAnswers: components["schemas"]["FillBlankAnswerDto"][];
        });
        UpdateMultipleQuestionApiRequest: {
            type: "UpdateMultipleQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["UpdateQuestionApiRequest"], "number">, "type"> & {
            choices: components["schemas"]["MultipleChoiceDto"][];
        });
        UpdateOrderingQuestionApiRequest: {
            type: "UpdateOrderingQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["UpdateQuestionApiRequest"], "number">, "type"> & {
            options: components["schemas"]["OrderingQuestionOptionDto"][];
        });
        UpdateQuestionApiRequest: {
            /** Format: int64 */
            id?: number;
            content?: string;
            explanation?: string;
            /** @description 업로드하려는 이미지의 url */
            imageUrl?: string;
            /**
             * Format: int64
             * @description 업로드하려는 이미지의 PK
             */
            imageId?: number;
            /**
             * Format: int64
             * @description 문제 번호, 단 문제 번호는 변경되지 않음
             */
            number: number;
            type: string;
        };
        UpdateShortQuestionApiRequest: {
            type: "UpdateShortQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["UpdateQuestionApiRequest"], "number">, "type"> & {
            shortAnswers: components["schemas"]["ShortAnswerDto"][];
        });
        ApiResponseQuestionApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["FillBlankQuestionApiResponse"] | components["schemas"]["MultipleQuestionApiResponse"] | components["schemas"]["OrderingQuestionApiResponse"] | components["schemas"]["ShortQuestionApiResponse"];
        };
        /** @description 빈칸 문제의 정답 목록 */
        FillBlankAnswerApiResponse: {
            /**
             * Format: int64
             * @description 빈칸 문제 답안 ID
             */
            id: number;
            answer?: string;
            /** @description 빈칸 문제 답안이 주관식인지 객관식인지 여부 */
            isMain: boolean;
            /**
             * Format: int64
             * @description 빈칸 문제 답안의 순서
             */
            number: number;
        };
        FillBlankQuestionApiResponse: {
            type: "FillBlankQuestionApiResponse";
        } & (Omit<WithRequired<components["schemas"]["QuestionApiResponse"], "id" | "type">, "type"> & {
            /** @description 빈칸 문제의 정답 목록 */
            answers?: components["schemas"]["FillBlankAnswerApiResponse"][];
            /**
             * Format: int32
             * @description 빈칸의 개수
             */
            blankCount: number;
        });
        /** @description 객관식 문제의 선택지 목록 */
        MultipleChoiceApiResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            number: number;
            content?: string;
            isCorrect: boolean;
        };
        MultipleQuestionApiResponse: {
            type: "MultipleQuestionApiResponse";
        } & (Omit<WithRequired<components["schemas"]["QuestionApiResponse"], "id" | "type">, "type"> & {
            /** @description 객관식 문제의 선택지 목록 */
            choices: components["schemas"]["MultipleChoiceApiResponse"][];
        });
        /** @description 순서 문제의 보기 목록 */
        OrderingOptionApiResponse: {
            /**
             * Format: int64
             * @description 정렬 문제 옵션 ID
             */
            id: number;
            /**
             * Format: int32
             * @description 정렬 문제 옵션의 원래 순서
             */
            originOrder: number;
            content?: string;
            /**
             * Format: int32
             * @description 정렬 문제 옵션의 답안 순서
             */
            answerOrder?: number;
        };
        OrderingQuestionApiResponse: {
            type: "OrderingQuestionApiResponse";
        } & (Omit<WithRequired<components["schemas"]["QuestionApiResponse"], "id" | "type">, "type"> & {
            /** @description 순서 문제의 보기 목록 */
            options: components["schemas"]["OrderingOptionApiResponse"][];
        });
        QuestionApiResponse: {
            /** Format: int64 */
            id: number;
            content?: string;
            explanation?: string;
            imageUrl?: string;
            /** Format: int64 */
            imageId?: number;
            /** Format: int64 */
            imageId?: number;
            /** Format: int64 */
            number?: number;
            /** @enum {string} */
            type: "SHORT" | "MULTIPLE" | "ORDERING" | "FILL_BLANK";
            /** @enum {string} */
            questionStatusType?: "NOT_OPEN" | "ACCESS_PERMISSION" | "SOLVE_PERMISSION";
        };
        /** @description 주관식 문제의 정답 목록 */
        ShortAnswerApiResponse: {
            /** Format: int64 */
            id: number;
            answer?: string;
            isMain: boolean;
            /** Format: int64 */
            number: number;
        };
        ShortQuestionApiResponse: {
            type: "ShortQuestionApiResponse";
        } & (Omit<WithRequired<components["schemas"]["QuestionApiResponse"], "id" | "type">, "type"> & {
            /** @description 주관식 문제의 정답 목록 */
            answers?: components["schemas"]["ShortAnswerApiResponse"][];
            /**
             * Format: int32
             * @description 주관식 문제의 정답 개수
             */
            answerCount: number;
        });
        UpdateActiveParticipantsRequest: {
            activeUserIds?: number[];
        };
        ApiResponseVoid: {
            isSuccess?: boolean;
            data?: Record<string, never>;
        };
        CreateTeamApiRequest: {
            name: string;
        };
        CreateTeamInviteApiRequest: {
            /** @enum {string} */
            duration: "ONE_DAY" | "THREE_DAYS" | "SEVEN_DAYS" | "NO_EXPIRATION";
        };
        ApiResponseCreateTeamInviteApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["CreateTeamInviteApiResponse"];
        };
        CreateTeamInviteApiResponse: {
            /** @description 팀 초대 토큰 */
            token: string;
        };
        CreateQuestionSetApiRequest: {
            /** Format: int64 */
            teamId: number;
            /** Format: int64 */
            teamId: number;
            subject: string;
            /** @enum {string} */
            creationType: "AI_GENERATED" | "MANUAL";
            /** @description 업로드한 해당 문제 셋의 파일 목록 */
            materials?: components["schemas"]["MaterialDto"][];
            /** @description 제작 요청할 문제 개수 */
            counts?: components["schemas"]["QuestionCount"][];
            /** @description 문제 난이도, AI 생성인 경우에만 활용 */
            difficulty?: string;
            /** @description 문제 셋에 대한 보충 설명, AI 생성인 경우에만 활용 */
            instruction?: string;
        };
        /** @description 업로드한 해당 문제 셋의 파일 목록 */
        MaterialDto: {
            /** Format: int64 */
            id?: number;
            url?: string;
        };
        /** @description 제작 요청할 문제 개수 */
        QuestionCount: {
            /** @enum {string} */
            type: "SHORT" | "MULTIPLE" | "ORDERING" | "FILL_BLANK";
            /** Format: int32 */
            count?: number;
            /** @description 업로드한 해당 문제 셋의 파일 목록 */
            materials?: components["schemas"]["MaterialDto"][];
            /** @description 제작 요청할 문제 개수 */
            counts?: components["schemas"]["QuestionCount"][];
            /** @description 문제 난이도, AI 생성인 경우에만 활용 */
            difficulty?: string;
            /** @description 문제 셋에 대한 보충 설명, AI 생성인 경우에만 활용 */
            instruction?: string;
        };
        /** @description 업로드한 해당 문제 셋의 파일 목록 */
        MaterialDto: {
            /** Format: int64 */
            id?: number;
            url?: string;
        };
        /** @description 제작 요청할 문제 개수 */
        QuestionCount: {
            /** @enum {string} */
            type: "SHORT" | "MULTIPLE" | "ORDERING" | "FILL_BLANK";
            /** Format: int32 */
            count?: number;
        };
        ApiResponseCreateQuestionSetApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["CreateQuestionSetApiResponse"];
        };
        CreateQuestionSetApiResponse: {
            /**
             * Format: int64
             * @description 생성된 문제 셋의 ID
             */
            questionSetId: number;
            /** @description 문제 셋 주제 */
            subject: string;
        };
        CreateFillBlankQuestionApiRequest: {
            type: "CreateFillBlankQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["CreateQuestionApiRequest"], "number">, "type"> & {
            fillBlankAnswers: components["schemas"]["FillBlankAnswerDto"][];
        });
        CreateMultipleQuestionApiRequest: {
            type: "CreateMultipleQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["CreateQuestionApiRequest"], "number">, "type"> & {
            choices: components["schemas"]["MultipleChoiceDto"][];
        });
        CreateOrderingQuestionApiRequest: {
            type: "CreateOrderingQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["CreateQuestionApiRequest"], "number">, "type"> & {
            options: components["schemas"]["OrderingQuestionOptionDto"][];
        });
        CreateQuestionApiRequest: {
            content?: string;
            explanation?: string;
            /** Format: int64 */
            number: number;
            type: string;
        };
        CreateShortQuestionApiRequest: {
            type: "CreateShortQuestionApiRequest";
        } & (Omit<WithRequired<components["schemas"]["CreateQuestionApiRequest"], "number">, "type"> & {
            shortAnswers: components["schemas"]["ShortAnswerDto"][];
        });
        FillBlankQuestionSubmitAnswer: {
            type: "FillBlankQuestionSubmitAnswer";
        } & (Omit<components["schemas"]["SubmitAnswerDtoObject"], "type"> & {
            submitAnswers?: components["schemas"]["FillBlankSubmitAnswer"][];
        } & Omit<components["schemas"]["SubmitAnswerDtoString"], "type"> & Omit<components["schemas"]["SubmitAnswerDtoLong"], "type"> & Omit<components["schemas"]["SubmitAnswerDtoFillBlankSubmitAnswer"], "type">);
        FillBlankQuestionSubmitApiRequest: {
            type: "FillBlankQuestionSubmitApiRequest";
        } & Omit<WithRequired<components["schemas"]["QuestionAnswerSubmitApiRequest"], "submitAnswers" | "userId">, "type">;
        FillBlankSubmitAnswer: {
            /** Format: int64 */
            number: number;
            answer: string;
        };
        MultipleQuestionSubmitAnswer: {
            type: "MultipleQuestionSubmitAnswer";
        } & (Omit<WithRequired<components["schemas"]["SubmitAnswerDtoObject"], "submitAnswers">, "type"> & {
            /** @description 선택한 번호 목록 */
            submitAnswers: number[];
        } & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoString"], "submitAnswers">, "type"> & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoLong"], "submitAnswers">, "type"> & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoFillBlankSubmitAnswer"], "submitAnswers">, "type">);
        MultipleQuestionSubmitApiRequest: {
            type: "MultipleQuestionSubmitApiRequest";
        } & Omit<WithRequired<components["schemas"]["QuestionAnswerSubmitApiRequest"], "submitAnswers" | "userId">, "type">;
        OrderingQuestionSubmitAnswer: {
            type: "OrderingQuestionSubmitAnswer";
        } & (Omit<WithRequired<components["schemas"]["SubmitAnswerDtoObject"], "submitAnswers">, "type"> & {
            /** @description 사용자가 입력한 답변 순서 */
            submitAnswers: number[];
        } & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoString"], "submitAnswers">, "type"> & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoLong"], "submitAnswers">, "type"> & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoFillBlankSubmitAnswer"], "submitAnswers">, "type">);
        OrderingQuestionSubmitApiRequest: {
            type: "OrderingQuestionSubmitApiRequest";
        } & Omit<WithRequired<components["schemas"]["QuestionAnswerSubmitApiRequest"], "submitAnswers" | "userId">, "type">;
        QuestionAnswerSubmitApiRequest: {
            /**
             * Format: int64
             * @description 문제 PK, 추후에 삭제 예정
             */
            userId: number;
            submitAnswers?: components["schemas"]["FillBlankQuestionSubmitAnswer"] | components["schemas"]["MultipleQuestionSubmitAnswer"] | components["schemas"]["OrderingQuestionSubmitAnswer"] | components["schemas"]["ShortQuestionSubmitAnswer"];
            type: string;
        };
        /** @enum {string} */
        QuestionType: "SHORT" | "MULTIPLE" | "ORDERING" | "FILL_BLANK";
        ShortQuestionSubmitAnswer: {
            type: "ShortQuestionSubmitAnswer";
        } & (Omit<WithRequired<components["schemas"]["SubmitAnswerDtoObject"], "submitAnswers">, "type"> & {
            /** @description 사용자가 입력한 답변 */
            submitAnswers: string[];
        } & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoString"], "submitAnswers">, "type"> & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoLong"], "submitAnswers">, "type"> & Omit<WithRequired<components["schemas"]["SubmitAnswerDtoFillBlankSubmitAnswer"], "submitAnswers">, "type">);
        ShortQuestionSubmitApiRequest: {
            type: "ShortQuestionSubmitApiRequest";
        } & Omit<WithRequired<components["schemas"]["QuestionAnswerSubmitApiRequest"], "submitAnswers" | "userId">, "type">;
        SubmitAnswerDtoFillBlankSubmitAnswer: {
            type?: components["schemas"]["QuestionType"];
            submitAnswers?: components["schemas"]["FillBlankSubmitAnswer"][];
        };
        SubmitAnswerDtoLong: {
            type?: components["schemas"]["QuestionType"];
            submitAnswers?: number[];
        };
        SubmitAnswerDtoObject: {
            type?: components["schemas"]["QuestionType"];
            submitAnswers?: Record<string, never>[];
        };
        SubmitAnswerDtoString: {
            type?: components["schemas"]["QuestionType"];
            submitAnswers?: string[];
        };
        ApiResponseQuestionAnswerSubmitApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionAnswerSubmitApiResponse"];
        };
        QuestionAnswerSubmitApiResponse: {
            /**
             * Format: int64
             * @description 제출한 기록 PK
             */
            id: number;
            /**
             * Format: int64
             * @description 제출한 유저 PK
             */
            userId: number;
            /**
             * Format: int64
             * @description 제출한 문제 PK
             */
            questionId: number;
            /** @description 정/오답 여부 */
            isCorrect: boolean;
        };
        FillBlankUpdateAnswerPayload: Omit<components["schemas"]["UpdateAnswerPayload"], "type"> & {
            answers: components["schemas"]["FillBlankAnswerDto"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FillBlankUpdateAnswerPayload";
        };
        MultipleChoiceUpdateAnswerPayload: Omit<components["schemas"]["UpdateAnswerPayload"], "type"> & {
            correctChoiceIds: number[];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultipleChoiceUpdateAnswerPayload";
        };
        OptionOrderPatch: {
            /** Format: int64 */
            optionId: number;
            /** Format: int32 */
            answerOrder?: number;
        };
        OrderingUpdateAnswerPayload: Omit<components["schemas"]["UpdateAnswerPayload"], "type"> & {
            options: components["schemas"]["OptionOrderPatch"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OrderingUpdateAnswerPayload";
        };
        ShortUpdateAnswerPayload: Omit<components["schemas"]["UpdateAnswerPayload"], "type"> & {
            shortAnswers: components["schemas"]["ShortAnswerDto"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ShortUpdateAnswerPayload";
        };
        /** @description 수정할 문제 값 */
        UpdateAnswerPayload: {
            type: string;
        } & (components["schemas"]["MultipleChoiceUpdateAnswerPayload"] | components["schemas"]["OrderingUpdateAnswerPayload"] | components["schemas"]["FillBlankUpdateAnswerPayload"] | components["schemas"]["ShortUpdateAnswerPayload"]);
        UpdateQuestionAnswerApiRequest: {
            /** @enum {string} */
            type: "SHORT" | "MULTIPLE" | "ORDERING" | "FILL_BLANK";
            payload: components["schemas"]["UpdateAnswerPayload"];
        };
        ApiResponseQuestionImageApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionImageApiResponse"];
        };
        QuestionImageApiResponse: {
            /**
             * Format: int64
             * @description 문제 이미지 아이디
             */
            id: number;
            /** @description 생성된 이미지 url */
            imageUrl: string;
        };
        SendWinnerRequest: {
            winnerUserIds?: number[];
        };
        ApiResponseQuestionSetMaterialApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionSetMaterialApiResponse"];
        };
        QuestionSetMaterialApiResponse: {
            /**
             * Format: int64
             * @description 업로드한 자료 PK
             */
            id: number;
            /** @description 업로드된 자료가 저장된 url */
            materialUrl: string;
        };
        CheckPoliciesApiRequest: {
            /** @description 체크할 정책 목록 */
            policyChecks: components["schemas"]["PolicyCheckRequest"][];
        };
        /** @description 체크할 정책 목록 */
        PolicyCheckRequest: {
            /**
             * Format: int64
             * @description 정책 ID
             */
            policyId: number;
            /** @description 동의 여부 */
            isChecked: boolean;
        };
        ApiResponseCheckPoliciesApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["CheckPoliciesApiResponse"];
        };
        CheckPoliciesApiResponse: {
            /** @description 성공 메시지 */
            message: string;
        };
        LoginApiRequest: {
            email: string;
            password: string;
        };
        UpdateNicknameRequest: {
            nickname: string;
        };
        ApiResponseUpdateNicknameResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["UpdateNicknameResponse"];
        };
        UpdateNicknameResponse: {
            /** @description 사용자 닉네임 */
            nickname: string;
            /** @description 사용자 전체 닉네임 */
            fullNickname: string;
        };
        UpdateQuestionSetFieldApiRequest: {
            title: string;
        };
        UpdateQuestionOrderApiRequest: {
            /**
             * Format: int64
             * @description 바로 앞에 올 문제 ID (없으면 null)
             */
            prevQuestionId?: number;
            /**
             * Format: int64
             * @description 바로 뒤에 올 문제 ID (없으면 null)
             */
            nextQuestionId?: number;
        };
        ApiResponseRandomNicknameResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["RandomNicknameResponse"];
        };
        RandomNicknameResponse: {
            /** @description 랜덤 닉네임 */
            nickname: string;
        };
        ApiResponseUserInfoApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["UserInfoApiResponse"];
        };
        UserInfoApiResponse: {
            /**
             * Format: int64
             * @description 사용자 ID
             */
            id?: number;
            /** @description 사용자 이름 */
            name?: string;
            /** @description 사용자 이메일 */
            email?: string;
            /** @description 사용자 닉네임 */
            nickname?: string;
            /** @description 사용자 전체 닉네임 */
            fullNickname?: string;
        };
        ApiResponseQuestionSetsApiResponse: {
        ApiResponseQuestionSetsApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionSetsApiResponse"];
        };
        /** @description 문제 셋 컨테이너 (QuestionSetList 또는 QuestionSetGroup) */
        QuestionSetContainer: components["schemas"]["QuestionSetList"] | components["schemas"]["QuestionSetGroup"];
        /** @description 진행 상태별로 그룹화된 문제 셋 (BEFORE: 시작 전, ONGOING: 진행 중, AFTER: 종료) */
        QuestionSetDto: {
            /** Format: int64 */
            id?: number;
            subject?: string;
            title?: string;
            /** @enum {string} */
            creationType?: "AI_GENERATED" | "MANUAL";
            /** @enum {string} */
            visibility?: "PUBLIC" | "GROUP" | "PRIVATE";
            /** @enum {string} */
            deliveryMode?: "MAKING" | "LIVE_TIME" | "REVIEW";
            /** @enum {string} */
            ongoingStatus?: "BEFORE" | "ONGOING" | "AFTER";
            /** Format: int64 */
            teamId?: number;
            /** Format: int64 */
            questionCount?: number;
            difficulty?: string;
            materials?: components["schemas"]["MaterialDto"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description 문제 셋 그룹 (진행 상태별로 그룹화된 Map 구조) */
        QuestionSetGroup: {
            /** @description 진행 상태별로 그룹화된 문제 셋 (BEFORE: 시작 전, ONGOING: 진행 중, AFTER: 종료) */
            questionSets?: {
                [key: string]: components["schemas"]["QuestionSetDto"][];
            };
        };
        /** @description 문제 셋 목록 (List 구조) */
        QuestionSetList: {
            /** @description 문제 셋 목록 */
            questionSets?: components["schemas"]["QuestionSetDto"][];
        };
        /** @description 문제 셋 목록 응답 */
        QuestionSetsApiResponse: {
            /**
             * @description 전달 모드 (MAKING: 제작 중, LIVE_TIME: 실시간, REVIEW: 복습)
             * @example MAKING
             * @enum {string}
             */
            mode?: "MAKING" | "LIVE_TIME" | "REVIEW";
            content?: components["schemas"]["QuestionSetContainer"];
        };
        ApiResponseListQuestionApiResponse: {
            isSuccess?: boolean;
            data?: (components["schemas"]["FillBlankQuestionApiResponse"] | components["schemas"]["MultipleQuestionApiResponse"] | components["schemas"]["OrderingQuestionApiResponse"] | components["schemas"]["ShortQuestionApiResponse"])[];
        };
        ApiResponseQuestionAnswerSubmitRecordsApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionAnswerSubmitRecordsApiResponse"];
        };
        /** @description 선착순 제출 기록으로 정렬된 제출 기록 목록 */
        QuestionAnswerSubmitRecordApiResponse: {
            /**
             * Format: int64
             * @description 제출 기록 PK
             */
            id: number;
            /**
             * Format: int64
             * @description 제출한 유저 PK
             */
            userId: number;
            /** @description 제출한 유저 이름 */
            userName?: string;
            /** @description 제출한 유저 닉네임 */
            userNickname?: string;
            /**
             * Format: int64
             * @description 제출한 문제 PK
             */
            questionId: number;
            /** @description 정/오답 여부 */
            isCorrect: boolean;
            /**
             * Format: int64
             * @description 제출 순서
             */
            submitOrder: number;
            submittedAnswer: components["schemas"]["SubmitAnswerDtoObject"];
        };
        QuestionAnswerSubmitRecordsApiResponse: {
            /**
             * Format: int64
             * @description 전체 기록 개수
             */
            totalCounts: number;
            /**
             * Format: int64
             * @description 정답자 수
             */
            correctUserCounts: number;
            /**
             * Format: int64
             * @description 오답자 수
             */
            incorrectUserCounts: number;
            /** @description 선착순 제출 기록으로 정렬된 제출 기록 목록 */
            submitRecords: components["schemas"]["QuestionAnswerSubmitRecordApiResponse"][];
        };
        ApiResponseQuestionScorerApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionScorerApiResponse"];
        };
        QuestionScorerApiResponse: {
            /**
             * Format: int64
             * @description 득점자 PK
             */
            id: number;
            /**
             * Format: int64
             * @description 문제 PK
             */
            questionId: number;
            /**
             * Format: int64
             * @description 득점한 사용자 PK
             */
            userId?: number;
            /** @description 득점한 사용자 이름 */
            userName?: string;
            /**
             * Format: int64
             * @description 득점 순서
             */
            submitOrder?: number;
        };
        ApiResponseQuestionSetLiveStatusResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionSetLiveStatusResponse"];
        };
        QuestionSetLiveStatusResponse: {
            /** Format: int64 */
            questionSetId?: number;
            /** @enum {string} */
            liveStatus?: "BEFORE" | "ONGOING" | "AFTER";
            liveStatus?: "BEFORE" | "ONGOING" | "AFTER";
        };
        ApiResponseParticipantsCorrectAnswerRankResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["ParticipantsCorrectAnswerRankResponse"];
        };
        ParticipantCorrectAnswerResponse: {
            participantInfos?: components["schemas"]["ParticipantInfoResponse"];
            /** Format: int64 */
            correctAnswerCount?: number;
        };
        ParticipantInfoResponse: {
            /**
             * Format: int64
             * @description 진출 유저 ID
             */
            userId: number;
            /**
             * Format: int64
             * @description 참여자 ID
             */
            participantId: number;
            /** @description 참여자 이름 */
            participantName: string;
        };
        ParticipantsCorrectAnswerRankResponse: {
            activeParticipants?: components["schemas"]["ParticipantCorrectAnswerResponse"][];
            eliminatedParticipants?: components["schemas"]["ParticipantCorrectAnswerResponse"][];
        };
        ApiResponseListParticipantInfoResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["ParticipantInfoResponse"][];
        };
        ApiResponseCurrentQuestionApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["CurrentQuestionApiResponse"];
        };
        CurrentQuestionApiResponse: {
            /** Format: int64 */
            questionSetId?: number;
            /** Format: int64 */
            questionId?: number;
            /** @enum {string} */
            questionStatusType?: "NOT_OPEN" | "ACCESS_PERMISSION" | "SOLVE_PERMISSION";
        };
        /** @enum {string} */
        AiRequestStatus: "PENDING" | "PROCESSING" | "COMPLETED" | "NOT_FOUND" | "FAILED";
        AiRequestStatusApiResponse: {
            /** Format: int64 */
            questionSetId: number;
            status: components["schemas"]["AiRequestStatus"];
        };
        ApiResponseAiRequestStatusApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["AiRequestStatusApiResponse"];
        };
        ApiResponseListQuestionValidationApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["QuestionValidationApiResponse"][];
        };
        QuestionValidationApiResponse: {
            /**
             * Format: int64
             * @description 문제 PK
             */
            questionId: number;
            /** @description 유효성 검사 여부 */
            isValid: boolean;
            /**
             * Format: int64
             * @description 문제 번호, 존재하지 않을 수 있음
             */
            number?: number;
        };
        ApiResponseListLatestPoliciesApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["LatestPoliciesApiResponse"][];
        };
        LatestPoliciesApiResponse: {
            /**
             * Format: int64
             * @description 정책 버전 ID
             */
            id: number;
            /** @description 정책 제목 */
            title: string;
            /** @description 정책 내용 */
            content: string;
            policyType: components["schemas"]["PolicyType"];
            timing: components["schemas"]["PolicyTiming"];
            category: components["schemas"]["PolicyCategory"];
        };
        /**
         * @description 정책 카테고리
         * @enum {string}
         */
        PolicyCategory: "TERMS_OF_SERVICE" | "PERSONAL_INFORMATION" | "MARKETING";
        /**
         * @description 정책 적용 타이밍
         * @enum {string}
         */
        PolicyTiming: "SIGN_UP";
        /**
         * @description 정책 동의 필수
         * @enum {string}
         */
        PolicyType: "ESSENTIAL" | "OPTIONAL";
        ApiResponseListUnconfirmedPoliciesApiResponse: {
            isSuccess?: boolean;
            data?: components["schemas"]["UnconfirmedPoliciesApiResponse"][];
        };
        UnconfirmedPoliciesApiResponse: {
            /**
             * Format: int64
             * @description 정책 버전 ID
             */
            id: number;
            /** @description 정책 제목 */
            title: string;
            /** @description 정책 내용 */
            content: string;
            policyType: components["schemas"]["PolicyType"];
            timing: components["schemas"]["PolicyTiming"];
            category: components["schemas"]["PolicyCategory"];
        };
        ApiResponseString: {
            isSuccess?: boolean;
            data?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSetApiResponse"];
                };
            };
        };
    };
    completeQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionSetApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSetApiResponse"];
                };
            };
        };
    };
    updateQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionSetFieldApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getQuestion: {
        parameters: {
            query?: {
                mode?: "MAKING" | "LIVE_TIME" | "REVIEW";
            };
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionApiResponse"];
                };
            };
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFillBlankQuestionApiRequest"] | components["schemas"]["UpdateMultipleQuestionApiRequest"] | components["schemas"]["UpdateOrderingQuestionApiRequest"] | components["schemas"]["UpdateShortQuestionApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionApiResponse"];
                };
            };
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getActiveParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListParticipantInfoResponse"];
                };
            };
        };
    };
    updateActiveParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActiveParticipantsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    createTeamInviteCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamInviteApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCreateTeamInviteApiResponse"];
                };
            };
        };
    };
    getQuestionSets: {
        parameters: {
            query: {
                mode: "MAKING" | "LIVE_TIME" | "REVIEW";
                teamId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSetsApiResponse"];
                    "*/*": components["schemas"]["ApiResponseQuestionSetsApiResponse"];
                };
            };
        };
    };
    createQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionSetApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCreateQuestionSetApiResponse"];
                };
            };
        };
    };
    getQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionApiResponse"];
                };
            };
        };
    };
    createQuestion: {
        parameters: {
            query: {
                type: string;
            };
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFillBlankQuestionApiRequest"] | components["schemas"]["CreateMultipleQuestionApiRequest"] | components["schemas"]["CreateOrderingQuestionApiRequest"] | components["schemas"]["CreateShortQuestionApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FillBlankQuestionSubmitApiRequest"] | components["schemas"]["MultipleQuestionSubmitApiRequest"] | components["schemas"]["OrderingQuestionSubmitApiRequest"] | components["schemas"]["ShortQuestionSubmitApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionAnswerSubmitApiResponse"];
                };
            };
        };
    };
    allowQuestionSolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    allowQuestionAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    regradeQuestionSubmitRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionAnswerApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    image: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionImageApiResponse"];
                };
            };
        };
    };
    createDefaultQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionApiResponse"];
                };
            };
        };
    };
    sendWinner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendWinnerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    uploadQuestionSetFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    material: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSetMaterialApiResponse"];
                };
            };
        };
    };
    checkPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckPoliciesApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCheckPoliciesApiResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateUserNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNicknameRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUpdateNicknameResponse"];
                };
            };
        };
    };
    changeQuestionOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionOrderApiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    startLiveQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    endLiveQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getRandomNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRandomNicknameResponse"];
                };
            };
        };
    };
    getUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserInfoApiResponse"];
                };
            };
        };
    };
    getSubmitRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionAnswerSubmitRecordsApiResponse"];
                };
            };
        };
    };
    getScorer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionScorerApiResponse"];
                };
            };
        };
    };
    getLiveStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSetLiveStatusResponse"];
                };
            };
        };
    };
    getCorrectAnswerRank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseParticipantsCorrectAnswerRankResponse"];
                };
            };
        };
    };
    getCurrentQuestionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCurrentQuestionApiResponse"];
                };
            };
        };
    };
    getAiRequestStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionSetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAiRequestStatusApiResponse"];
                };
            };
        };
    };
    validateQuestionSet: {
        parameters: {
            query: {
                questionSetId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionValidationApiResponse"];
                };
            };
        };
    };
    findLatestPolicies: {
        parameters: {
            query: {
                timing: "SIGN_UP";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLatestPoliciesApiResponse"];
                };
            };
        };
    };
    findUnConfirmedPolicies: {
        parameters: {
            query: {
                timing: "SIGN_UP";
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListUnconfirmedPoliciesApiResponse"];
                };
            };
        };
    };
    getAccessToken: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
