export enum QuestionStatusType {
	NOT_OPEN = "NOT_OPEN",
	ACCESS_PERMISSION = "ACCESS_PERMISSION",
	SOLVE_PERMISSION = "SOLVE_PERMISSION",
	QUALIFIER = "QUALIFIER",
	WINNER = "WINNER",
}

export enum QuestionType {
	SHORT = "SHORT",
	MULTIPLE = "MULTIPLE",
	FILL_BLANK = "FILL_BLANK",
	ORDERING = "ORDERING",
}
